# Generated by Django 2.2.10 on 2020-10-06 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 20, 32, 7, 232076, tzinfo=utc)),
        ),
    ]
