# Generated by Django 2.2.10 on 2020-10-06 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_product_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 20, 41, 43, 564037, tzinfo=utc)),
        ),
    ]
