# Generated by Django 2.2.10 on 2020-10-07 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_auto_20201006_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 12, 11, 511536, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('information', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 12, 11, 511536, tzinfo=utc))),
                ('products', models.ManyToManyField(to='Market.Product')),
            ],
        ),
    ]
