# Generated by Django 2.2.10 on 2020-10-07 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_auto_20201007_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 14, 40, 271818, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 14, 40, 270821, tzinfo=utc)),
        ),
    ]
