# Generated by Django 2.2.10 on 2020-10-07 15:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0005_auto_20201007_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 0, 51, 131772, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 0, 51, 130776, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(through='Market.Cart', to='Market.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('product', 'order')},
        ),
    ]
