# Generated by Django 2.2.10 on 2020-10-07 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0006_auto_20201007_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='order_status',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 55, 23, 579137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 15, 55, 23, 578145, tzinfo=utc)),
        ),
    ]
