# Generated by Django 2.2.10 on 2020-10-07 20:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0008_auto_20201007_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 20, 24, 9, 352288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 20, 24, 9, 353285, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 20, 24, 9, 351291, tzinfo=utc)),
        ),
    ]
