# Generated by Django 2.2.10 on 2020-10-11 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0009_auto_20201007_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 14, 29, 27, 756548, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 14, 29, 27, 755552, tzinfo=utc)),
        ),
    ]
