# Generated by Django 2.2.10 on 2020-10-11 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0010_auto_20201011_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 14, 31, 48, 240449, tzinfo=utc)),
        ),
    ]
