# Generated by Django 2.2.10 on 2020-10-11 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0013_auto_20201011_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 15, 50, 42, 231695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
