# Generated by Django 2.2.10 on 2020-10-11 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0016_auto_20201011_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 17, 14, 5, 533290, tzinfo=utc)),
        ),
    ]
